spring:
  application:
    name: demo
  profiles: local
  datasource:
    url: jdbc:postgresql://localhost:5432/dados-prop
    username: psdev
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
  sql:
    init:
      platform: postgresql
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql

---
spring:
  profiles: des
  datasource:
    url: jdbc:postgresql://localhost:5432/dados-prop
    username: psdev
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    show-sql: true

